ARG BASEIMG
ARG IMG_VERSION
FROM $BASEIMG:$IMG_VERSION

ARG ENTRYPOINT

WORKDIR /app
ENV ASPNETCORE_URLS="http://+:8080" \
    RUNTIME=$ENTRYPOINT
EXPOSE 8080

COPY ./app .
COPY ./.ci/docker_entrypoint.sh .

RUN chmod +x /app/docker_entrypoint.sh \
    && chmod +x /app \
    && chmod -R 755 /app

ENTRYPOINT [ "/app/docker_entrypoint.sh" ]
